// frontend/components/Button.vue
<template>
  <button 
    :class="`${baseStyles} ${variants[variant]} ${className}`"
    :disabled="isLoading || disabled"
    v-bind="$attrs"
    @click="$emit('click', $event)"
  >
    <span class="relative z-10 flex items-center">
      <template v-if="isLoading">
        <svg class="animate-spin -ml-1 mr-3 h-4 w-4 text-current" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
          <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
          <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
        </svg>
        Processing
      </template>
      <template v-else>
        <slot />
      </template>
    </span>
  </button>
</template>

<script setup>
const props = defineProps({
  variant: {
    type: String,
    default: 'primary',
    validator: (value) => ['primary', 'secondary', 'outline'].includes(value)
  },
  isLoading: {
    type: Boolean,
    default: false
  },
  className: {
    type: String,
    default: ''
  },
  disabled: {
    type: Boolean,
    default: false
  }
})

defineEmits(['click'])

const baseStyles = "inline-flex items-center justify-center px-10 py-4 text-xs font-bold transition-all duration-500 rounded-none disabled:opacity-50 disabled:cursor-not-allowed tracking-[0.2em] uppercase relative overflow-hidden group"

const variants = {
  primary: "bg-luxury-gold text-black hover:bg-white hover:text-black border border-transparent",
  secondary: "bg-white text-black hover:bg-gray-200",
  outline: "border border-white text-white hover:bg-white hover:text-black"
}
</script>

// ubuntu-travels---expediciones-africanas/components/Button.tsx
import React from 'react';

interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'primary' | 'secondary' | 'outline';
  isLoading?: boolean;
}

export const Button: React.FC<ButtonProps> = ({ 
  children, 
  variant = 'primary', 
  className = '', 
  isLoading = false,
  ...props 
}) => {
  const baseStyles = "inline-flex items-center justify-center px-10 py-4 text-xs font-bold transition-all duration-500 rounded-none disabled:opacity-50 disabled:cursor-not-allowed tracking-[0.2em] uppercase relative overflow-hidden group";
  
  const variants = {
    primary: "bg-luxury-gold text-black hover:bg-white hover:text-black border border-transparent",
    secondary: "bg-white text-black hover:bg-gray-200",
    outline: "border border-white text-white hover:bg-white hover:text-black"
  };

  return (
    <button 
      className={`${baseStyles} ${variants[variant]} ${className}`}
      disabled={isLoading || props.disabled}
      {...props}
    >
      <span className="relative z-10 flex items-center">
        {isLoading ? (
          <>
            <svg className="animate-spin -ml-1 mr-3 h-4 w-4 text-current" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
            </svg>
            Processing
          </>
        ) : children}
      </span>
    </button>
  );
};
